---
title: "Energie"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      navbar-bg: "#da6d3a"
    source_code: embed 
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(plotly)
library(leaflet)
library(sf)
library(tmap)
library(shiny)
```

Biogas
=======================================================================

### Karte der Biogasanlagen

```{r}
biog <- read_sf("data/BiogasPlants.gpkg", layer="BiogasPlant") %>% 
  st_transform(4326) %>% 
  mutate(CombinedHeatAndPower = as.numeric(CombinedHeatAndPower))
  
leaflet(biog) %>% 
  addTiles(attribution = "Quelle: Bundesamt für Energie") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addCircleMarkers(fill = T,
                   fillColor = "brown",
                   #opacity = 0.8,
                   fillOpacity = 0.7,
                   color = NA, 
                   group = "Biogas",
                   radius = ifelse(!is.na(biog$CombinedHeatAndPower),
                                   biog$CombinedHeatAndPower %>% log() %>% sqrt() * 2,1),
                   popup = paste0("<b>Betreiber: </b>", biog$Name,"<br>",
                                  "<b>In Betrieb seit: </b>", biog$BeginningOfOperation, "<br>",
                                  "<b>Leistung kombiniert: </b>", round(biog$CombinedHeatAndPower,1), " kW")) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner Lite"),
    overlayGroups = c("Biogas"),
    options = layersControlOptions(collapsed = TRUE))
```

Windenergie
=======================================================================

### Karte des Windenergiepotentials und der bereits erstellten Windenergieanlagen

```{r}
windpot <- terra::rast("data/rastermap_v200605_einfarbig.tif") %>% terra::project("epsg:4326")
windanl <- read_sf("data/Windenergyplants.gpkg") %>% st_transform(4326) %>% 
  dplyr::filter(is.na(yearOfDismantling))


leaflet(windanl,
        options = leafletOptions(minZoom = 7, maxZoom = 7)) %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addCircles(fill = F,
                   color = "brown",
                   radius = 2,
                   opacity = 0.8,
                   group = "Wind",
                   popup = paste0("Hersteller: ", windanl$manufacturer,"<br>",
                                  "Gebaut im Jahr ", windanl$yearOfConstruction, "<br>",
                                  "Richtwert Leistung: ", round(windanl$ratedPower,1))) %>% 
  addTiles(attribution = "Quelle: Bundesamt für Energie") %>% 
  addRasterImage(windpot %>% as(., "Raster"), 
                 colors = "chocolate1", 
                 opacity = 0.3,
                 group = "Wind") %>% 
  addLegend(title = "Windpotential",
            colors = c("brown", NA),
            labels = c("vorhanden", "nicht vorhanden")) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner Lite"),
    overlayGroups = c("Wind"),
    options = layersControlOptions(collapsed = TRUE))

```

Shiny
=======================================================================


Column {.sidebar data-width=150}
-----------------------------------------------------------------------

```{r}
sliderInput('pow', 'Leistung', min=5, max=2200,
            value=median(biog$CombinedHeatAndPower, na.rm=T))

# reactive({print(input$pow)})

```

Column
-----------------------------------------------------------------------

### Karte Biogas, Auswahl nach kombinierter Leistung

```{r}

# save selected data
selectedData <- reactive({
  biog[biog$CombinedHeatAndPower >= input$pow,]
})

# reactive({selectedData()})

renderLeaflet({
  leaflet(selectedData(),
          options = leafletOptions(minZoom = 7, maxZoom = 7)) %>% 
    fitBounds(6,45.8,10.5,48) %>% 
  addTiles(attribution = "Quelle: Bundesamt für Energie") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addCircleMarkers(fill = T,
                   fillColor = "brown",
                   #opacity = 0.8,
                   fillOpacity = 0.7,
                   color = NA, 
                   group = "Biogas",
                   radius = ifelse(!is.na(biog$CombinedHeatAndPower),
                                   biog$CombinedHeatAndPower %>% log() %>% sqrt() * 2,1),
                   popup = paste0("<b>Betreiber: </b>", biog$Name,"<br>",
                                  "<b>In Betrieb seit: </b>", biog$BeginningOfOperation, "<br>",
                                  "<b>Leistung kombiniert: </b>", round(biog$CombinedHeatAndPower,1), " kW")) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner Lite"),
    overlayGroups = c("Biogas"),
    options = layersControlOptions(collapsed = TRUE))
  })
```













